### ISSUE TITLE
Test Generator in ePMP test-suite and Spike need update for missing/incorrect cases

### ISSUE THREAD

**Issue by mohsinshahbaz-10xe** [joxie/riscv-isa-sim#1]
I noticed some issues in the generated tests from _gen_pmp_test.cc_ and _test_pmp_ok_1.cc_skel._

**First,** the expected behavior in the generated tests is to ignore all the accesses (read/write/execute) in case of _test_pmp_ok_1_u0_*_match0_mmwp0_mml1.c_

In the case of machine mode, when the address mismatch occurs and MMWP is set to 0 and MML is set to 1, then only read/write access should be ignored and execution access should be denied according to Visual Representation of the proposal in the RISC-V ePMP Spec. 

The tests are falsely passing on Spike updated with ePMP spec because it also does not cover this scenario in its implementation.

**Second,** the case RW=01 with MML=0 is reserved for future use. But generated tests _test_pmp_ok_1_u*_rw01_*_mml0_ are expecting access permissions in such a way that this case is implemented as RW=00. I think this case should be dealt with in a way that it is not dependent on implementation in simulators or actual hardware.

Please let me know if there is anything which I am missing while understanding the spec.

Thanks

**Comment by soberl** [comment]
For second issue, just updated the generator to avoid test cases this combination.

**Comment by saadkhalid-10xe** [comment]
@soberl thanks for updating for the second issue.

For the first one, following seems to be the proposed fix.
```
--- a/tests/mseccfg/gengen_src/gen_pmp_test.cc
+++ b/tests/mseccfg/gengen_src/gen_pmp_test.cc
@@ -117,6 +117,8 @@ main()
         if (u_mode == 1 || mmwp) { // mmwp to against non-match
             rw_err = 1;
             x_err = 1;
+        } else if (mml == 1) {
+            x_err = 1;
         }
     }
```

**Comment by soberl** [comment]
I have reviewed changes and confirm it's working (spike + test cases). Thanks for the help.
I will go on work on RISC-V sail mode (https://github.com/joxie/sail-riscv/), if you haven't touch it @saadkhalid-10xe

**Comment by mohsinshahbaz-10xe** [comment]
Thanks @saadkhalid-10xe, the issue is resolved.
