### ISSUE TITLE
ePMP test suite bug with MML=1 and rule 4b

### ISSUE THREAD

**Issue by pdonahue-ventana** [joxie/riscv-isa-sim#7]
@joxie, I think that there is a bug in this ePMP test suite.

For instance, [test_pmp_csr_1_lock01_rlb0_mmwp0_mml1_pmp_01](https://github.com/joxie/riscv-isa-sim/blob/ac65ae16aa9724ebf0810e6388361707f67829ea/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock01_rlb0_mmwp0_mml1_pmp_01.c) does the following:
- pmpcfg0[31:24]=0x8F, mseccfg.MML=0, mseccfg.RLB=1 as of [line 126](https://github.com/joxie/riscv-isa-sim/blob/ac65ae16aa9724ebf0810e6388361707f67829ea/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock01_rlb0_mmwp0_mml1_pmp_01.c#L126)
- [Line 187](https://github.com/joxie/riscv-isa-sim/blob/ac65ae16aa9724ebf0810e6388361707f67829ea/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock01_rlb0_mmwp0_mml1_pmp_01.c#L187) clears the lock bit (which is fine since RLB=1).  Now pmpcfg0[31:24]=0x0F.
- [Line 198](https://github.com/joxie/riscv-isa-sim/blob/ac65ae16aa9724ebf0810e6388361707f67829ea/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock01_rlb0_mmwp0_mml1_pmp_01.c#L198) clears RLB and sets MML
- [Line 228](https://github.com/joxie/riscv-isa-sim/blob/ac65ae16aa9724ebf0810e6388361707f67829ea/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock01_rlb0_mmwp0_mml1_pmp_01.c#L228) writes 0x8E to [31:24].  This has LRWX=1011 which is adding a locked shared code region.

The spec (rule 4b) says that when MML=1:
> Adding a rule with executable privileges that either is M-mode-only or a locked Shared-Region is not possible and such pmpcfg writes are ignored, leaving pmpcfg unchanged.

Therefore, the attempted write of 0x8E should be ignored and pmpcfg0[31:24] should remain 0x0F.  However, [line 233](https://github.com/joxie/riscv-isa-sim/blob/ac65ae16aa9724ebf0810e6388361707f67829ea/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock01_rlb0_mmwp0_mml1_pmp_01.c#L233) expects the update to have happened.

There are a few other tests that fail for similar reasons.

**Comment by joxie** [comment]
@soberl can you check the test?

**Comment by soberl** [comment]
The commit for test suite close this issue automatically :)
Reopen this until @joxie fix the spike impl.

**Comment by joxie** [comment]
Test and Spike updated. @pdonahue-ventana  can you check the test again before we can close this issue?

**Comment by soberl** [comment]
I just realized that the previous test suite is not taken PMP_L as independent input. E.g., when @lock_once:int@ and @pmp_lock:int@ are both 0, the PMP_L will not be set later since @revert_rwx:int@ loop from 1 to 7. Let me update the test suite later again.

**Comment by joxie** [comment]
@pdonahue-ventana let us know if you are good to close this issue

**Comment by pdonahue-ventana** [comment]
I had some failures but I haven't had a chance to see if those are test problems or something else.

**Comment by pdonahue-ventana** [comment]
I just looked at a failure with https://github.com/joxie/riscv-isa-sim/blob/master/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock10_rlb0_mmwp0_mml1_pmp_06.c

I see pmpcfg0[23:16]=0x8f on [line 181](https://github.com/joxie/riscv-isa-sim/blob/master/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock10_rlb0_mmwp0_mml1_pmp_06.c#L181).  I see mseccfg=1 (MML=1, RLB=0) on [line 198](https://github.com/joxie/riscv-isa-sim/blob/master/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock10_rlb0_mmwp0_mml1_pmp_06.c#L198).  So entry 2 should be a locked shared data region which "cannot be removed or modified until a PMP reset" according to the spec.

[Line 216](https://github.com/joxie/riscv-isa-sim/blob/master/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock10_rlb0_mmwp0_mml1_pmp_06.c#L216) tries to write 0x120000 to pmpaddr2 (replacing the 0x90000 that was previously there).  The test expects the write to be successful but I think that the write should be ignored and 0x90000 should remain.

I have 47 total test failures but I assume that they'll all be similar.

**Comment by pdonahue-ventana** [comment]
I just looked at another one and it's a different problem.

https://github.com/joxie/riscv-isa-sim/blob/master/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock01_rlb1_mmwp1_mml0_pmp_01.c tries to write 0xfff4f3ff8e0f0000 to pmpcfg0 and expects to read that same value back.  Note that the top byte is all ones.  The test's expectation is obviously wrong since [6:5] of each pmpcfg byte is 0 so you can't ever read ones there, regardless of what mode things are in.

**Comment by soberl** [comment]
For test_pmp_csr_1_lock01_rlb1_mmwp1_mml0_pmp_01.c, line 227 has read the pmpcfg0 once, and line 234 to write and read back again. So the test just focus on index 3 indeed, which is 0x8e. And the expected_pmpcfg_fail = 1 is set already because of PMP_L && PMP_X.

**Comment by soberl** [comment]
> 
For test_pmp_csr_1_lock10_rlb0_mmwp0_mml1_pmp_06.c,
The test expects "expected_pmpaddr_fail = 1;" at line 77. What's ur mean for "test expects the write to be successful"?

**Comment by pdonahue-ventana** [comment]
I mean that this code:
```
    asm volatile ("csrw pmpaddr2, %1 \n"
                "\tcsrr %0, pmpaddr2 \n"
            : "=r"(rval)
            : "r"(wval)
              : "memory");
    if (wval != rval) {
```
writes a value to pmpaddr2 and then reads pmpaddr2 and expects the read value to match the written value.  But if the entry is locked then the read will return the old value rather than the value that was attempted to be written in that asm block.

**Comment by soberl** [comment]
Yes, so the write action is expected to be failed. Thus "expected_pmpaddr_fail = 1;" is set. Is there any misunderstanding here?

**Comment by pdonahue-ventana** [comment]
You're right.  I'll redo my analysis.
