### ISSUE TITLE
Test expects that creating a new locked shared data region rule will fail

### ISSUE THREAD

**Issue by pdonahue-ventana** [joxie/riscv-isa-sim#8]
https://github.com/joxie/riscv-isa-sim/blob/master/tests/mseccfg/gengen_src/outputs/test_pmp_csr_1_lock01_rlb0_mmwp0_mml1_pmp_17.c has:
```
static const unsigned long expected_pmpcfg_fail = 1;
```
It changes one of the bytes of pmpcfg2 from 0x00 to 0x87.  That goes from inaccessible to a locked shared data region.  This is adding a new locked rule that is not executable so [rule 4b](https://github.com/riscv/riscv-tee/blob/main/Smepmp/Proposal.adoc) ("Adding a rule with executable privileges that either is M-mode-only or a locked Shared-Region is not possible") does not apply.  I don't see any other reason that this pmpcfg change might be expected to fail.

I see the same thing on test_pmp_csr_1_lock01_rlb0_mmwp1_mml1_pmp_17.c (which isn't surprising since the only difference is MMWP which doesn't affect this particular behavior).

@soberl

**Comment by soberl** [comment]
Yes, indeed. We will fix it. Thanks for the notification.

**Comment by soberl** [comment]
Update test case with https://github.com/joxie/riscv-isa-sim/commit/c2186bf1731b2a123ccc785ce9585861d370886f

**Comment by pdonahue-ventana** [comment]
Looks good.  Thanks.
